name: new_env_pyro2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ca-certificates=2024.12.31
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - ansicolors==1.1.8
      - anyio==4.8.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arviz==0.17.1
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - babel==2.17.0
      - beautifulsoup4==4.13.1
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==5.5.1
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.1
      - comm==0.2.2
      - cons==0.4.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dtaidistance==2.3.13
      - entrypoints==0.4
      - etuples==0.3.10
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fastprogress==1.0.3
      - filelock==3.16.1
      - fonttools==4.55.3
      - formulaic==1.1.1
      - fqdn==1.5.1
      - fsspec==2024.10.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - graphviz==0.20.3
      - h11==0.14.0
      - h5netcdf==1.6.3
      - h5py==3.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.4.5
      - interface-meta==1.3.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lifelines==0.30.0
      - logical-unification==0.4.6
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - minikanren==1.0.5
      - mistune==3.1.1
      - mpmath==1.3.0
      - multipledispatch==1.0.0
      - narwhals==1.26.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - papermill==2.6.0
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.0
      - pycparser==2.22
      - pydeck==0.9.1
      - pygments==2.19.1
      - pymc==5.7.2
      - pyparsing==3.2.0
      - pysocks==1.7.1
      - pytensor==2.14.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - quarto==0.1.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - rpy2==3.5.17
      - scikit-learn==1.6.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - streamlit==1.42.0
      - sympy==1.13.1
      - tenacity==9.0.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.5.1
      - torch-lr-finder==0.2.2
      - torchviz==0.0.3
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - tzlocal==5.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xarray==2024.7.0
      - xarray-einstats==0.7.0
      - zipp==3.21.0
prefix: /opt/miniconda3/envs/new_env_pyro2
